import{redirect}from"next/navigation";
import{completeOnboardingAction}from"@/app/(app)/onboarding/actions";
import{createClient}from"@/lib/supabase/server";
export const metadata={title:"Настройка"};
export default async function Page({searchParams}:{searchParams:Promise<{error?:string}>}){
 const p=await searchParams;const s=await createClient();const{data:claims}=await s.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect("/login");
 const{data:profile}=await s.from("profiles").select("onboarding_completed").eq("id",userId).maybeSingle();if(profile?.onboarding_completed)redirect("/dashboard");
 return <div className="mx-auto max-w-2xl py-5 sm:py-10"><span className="inline-flex rounded-full bg-[var(--accent-soft)] px-3 py-1 text-sm font-black text-[var(--accent-strong)]">Первичная настройка</span><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Давайте разберёмся с вашими финансами</h1><p className="muted mt-4 max-w-xl leading-7">Создадим валюту, первый счёт, ориентир дохода и минимальную подушку. Всё можно изменить позже.</p>{p.error?<p className="mt-5 rounded-2xl bg-red-500/10 p-4 font-semibold text-[var(--danger)]">{p.error}</p>:null}<form action={completeOnboardingAction} className="card mt-7 space-y-5 p-6 sm:p-8"><label className="block text-sm font-bold">Как к вам обращаться<input className="field mt-2" name="displayName" placeholder="Илья" autoComplete="name" required/></label><label className="block text-sm font-bold">Основная валюта<select className="field mt-2" name="currency" defaultValue="RUB"><option value="RUB">RUB ₽</option><option value="USD">USD $</option><option value="EUR">EUR €</option></select></label><label className="block text-sm font-bold">Сколько денег сейчас на основной карте<input className="field mt-2" name="initialBalance" inputMode="decimal" placeholder="100 000" required/></label><label className="block text-sm font-bold">Средний ежемесячный доход<input className="field mt-2" name="monthlyIncome" inputMode="decimal" placeholder="150 000" required/></label><label className="block text-sm font-bold">Желаемая финансовая подушка<select className="field mt-2" name="emergencyFundMonths" defaultValue="3"><option value="1">1 месяц</option><option value="3">3 месяца</option><option value="6">6 месяцев</option><option value="12">12 месяцев</option></select></label><button className="btn-primary w-full">Создать финансовый профиль</button></form></div>
}
