import {
  ShoppingBasket,
  Utensils,
  House,
  ReceiptText,
  Bus,
  Car,
  HeartPulse,
  Sparkles,
  Shirt,
  Film,
  Repeat,
  GraduationCap,
  Plane,
  Baby,
  Gift,
  Landmark,
  Smartphone,
  BriefcaseBusiness,
  Wallet,
  Coins,
  ChartNoAxesCombined,
  ArrowLeftRight,
  Tag,
  Target,
  Palmtree,
  Laptop,
  BookOpen,
  type LucideIcon,
} from "lucide-react";
const icons: Record<string, LucideIcon> = {
  "🛒": ShoppingBasket,
  "🍽️": Utensils,
  "🏠": House,
  "🏡": House,
  "🧾": ReceiptText,
  "🚌": Bus,
  "🚗": Car,
  "🚕": Car,
  "🩺": HeartPulse,
  "✨": Sparkles,
  "👕": Shirt,
  "🎬": Film,
  "🔁": Repeat,
  "📚": BookOpen,
  "✈️": Plane,
  "🧸": Baby,
  "🎁": Gift,
  "🏦": Landmark,
  "📱": Smartphone,
  "💼": BriefcaseBusiness,
  "📑": ReceiptText,
  "💰": Coins,
  "📈": ChartNoAxesCombined,
  "🛠️": BriefcaseBusiness,
  "📊": ChartNoAxesCombined,
  "↩️": ArrowLeftRight,
  "🏷️": Tag,
  "🎯": Target,
  "🌴": Palmtree,
  "💻": Laptop,
  "🎓": GraduationCap,
};
export function Glyph({ value, size = 18 }: { value: string; size?: number }) {
  const Icon = icons[value] ?? Wallet;
  return <Icon size={size} aria-hidden="true" />;
}
