import {
  ShoppingBasket,
  Utensils,
  House,
  ReceiptText,
  Bus,
  Car,
  HeartPulse,
  Sparkles,
  Shirt,
  Film,
  Repeat,
  BookOpen,
  Plane,
  Baby,
  Gift,
  Landmark,
  Smartphone,
  BriefcaseBusiness,
  Coins,
  ChartNoAxesCombined,
  ArrowLeftRight,
  Tag,
  Target,
  Palmtree,
  Laptop,
  GraduationCap,
  Wallet,
  Coffee,
  PawPrint,
  Dumbbell,
  Wrench,
  Ellipsis,
  type LucideIcon,
} from "lucide-react";
import { normalizeIconId, type IconId } from "@/lib/domain/icons";
const icons: Record<IconId, LucideIcon> = {
  basket: ShoppingBasket,
  utensils: Utensils,
  home: House,
  receipt: ReceiptText,
  bus: Bus,
  car: Car,
  health: HeartPulse,
  beauty: Sparkles,
  clothes: Shirt,
  film: Film,
  repeat: Repeat,
  book: BookOpen,
  plane: Plane,
  baby: Baby,
  gift: Gift,
  bank: Landmark,
  phone: Smartphone,
  business: BriefcaseBusiness,
  coins: Coins,
  chart: ChartNoAxesCombined,
  transfer: ArrowLeftRight,
  tag: Tag,
  target: Target,
  palm: Palmtree,
  laptop: Laptop,
  education: GraduationCap,
  wallet: Wallet,
  coffee: Coffee,
  pet: PawPrint,
  sport: Dumbbell,
  tools: Wrench,
  other: Ellipsis,
};
export function Glyph({ value, size = 18 }: { value: string; size?: number }) {
  const Icon = icons[normalizeIconId(value)];
  return <Icon size={size} aria-hidden="true" />;
}
