import type{AccountBalance,BudgetProjectionInput,FinanceTransaction,ForecastItem,GoalProjectionInput,SafeToSpendInput}from "@/lib/finance/types";
export function calculateTotalBalance(accounts:AccountBalance[]){return accounts.filter(a=>a.includeInTotal!==false).reduce((t,a)=>t+a.balanceMinor,0);}
export function calculateCashFlow(transactions:Pick<FinanceTransaction,"type"|"amountMinor">[]){const incomeMinor=transactions.filter(t=>t.type==="income").reduce((s,t)=>s+t.amountMinor,0);const expensesMinor=transactions.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amountMinor,0);return{incomeMinor,expensesMinor,netMinor:incomeMinor-expensesMinor};}
export function calculateSavingsRate(incomeMinor:number,expensesMinor:number){return incomeMinor<=0?0:((incomeMinor-expensesMinor)/incomeMinor)*100;}
export function calculateEmergencyFundMonths(liquidSavingsMinor:number,averageMandatoryMonthlyExpensesMinor:number){return averageMandatoryMonthlyExpensesMinor<=0?0:liquidSavingsMinor/averageMandatoryMonthlyExpensesMinor;}
export function calculateSafeToSpend(i:SafeToSpendInput){return Math.max(0,i.liquidBalanceMinor-i.obligationsUntilNextIncomeMinor-i.reservedGoalMoneyMinor-i.minimumEmergencyReserveMinor);}
export function calculateGoalProjection(i:GoalProjectionInput){const remaining=Math.max(0,i.targetMinor-i.savedMinor);if(remaining===0)return 0;if(i.monthsRemaining<=0)return remaining;return Math.ceil(remaining/i.monthsRemaining);}
export function calculateBudgetProjection(i:BudgetProjectionInput){const elapsed=Math.max(1,i.elapsedDays);const projectedMinor=Math.round((i.spentMinor/elapsed)*i.totalDays);return{projectedMinor,usage:i.budgetMinor>0?i.spentMinor/i.budgetMinor:0,remainingMinor:Math.max(0,i.budgetMinor-i.spentMinor),willExceed:projectedMinor>i.budgetMinor};}
export function calculateForecast(currentBalanceMinor:number,items:ForecastItem[],estimatedVariableExpensesMinor=0){const plannedNet=items.reduce((s,i)=>s+(i.type==="income"?i.amountMinor:-i.amountMinor),0);return currentBalanceMinor+plannedNet-estimatedVariableExpensesMinor;}
export function applyTransactionToBalances(accounts:AccountBalance[],t:FinanceTransaction){const next=accounts.map(a=>({...a}));const source=next.find(a=>a.id===t.accountId);if(!source)throw new Error("Source account not found");if(t.type==="income")source.balanceMinor+=t.amountMinor;if(t.type==="expense")source.balanceMinor-=t.amountMinor;if(t.type==="transfer"){if(!t.destinationAccountId)throw new Error("Destination account is required");const destination=next.find(a=>a.id===t.destinationAccountId);if(!destination)throw new Error("Destination account not found");if(destination.id===source.id)throw new Error("Source and destination accounts must differ");source.balanceMinor-=t.amountMinor;destination.balanceMinor+=t.amountMinor;}return next;}
