export const DEFAULT_CATEGORIES = [
  { kind: "expense", name: "Продукты", icon: "basket" },
  { kind: "expense", name: "Кафе и рестораны", icon: "utensils" },
  { kind: "expense", name: "Дом", icon: "home" },
  { kind: "expense", name: "ЖКХ", icon: "receipt" },
  { kind: "expense", name: "Транспорт", icon: "bus" },
  { kind: "expense", name: "Автомобиль", icon: "car" },
  { kind: "expense", name: "Такси", icon: "car" },
  { kind: "expense", name: "Здоровье", icon: "health" },
  { kind: "expense", name: "Красота", icon: "beauty" },
  { kind: "expense", name: "Одежда", icon: "clothes" },
  { kind: "expense", name: "Развлечения", icon: "film" },
  { kind: "expense", name: "Подписки", icon: "repeat" },
  { kind: "expense", name: "Образование", icon: "book" },
  { kind: "expense", name: "Путешествия", icon: "plane" },
  { kind: "expense", name: "Дети", icon: "baby" },
  { kind: "expense", name: "Подарки", icon: "gift" },
  { kind: "expense", name: "Кредиты", icon: "bank" },
  { kind: "expense", name: "Связь", icon: "phone" },
  { kind: "expense", name: "Бизнес", icon: "business" },
  { kind: "expense", name: "Налоги", icon: "receipt" },
  { kind: "expense", name: "Другое", icon: "other" },
  { kind: "income", name: "Зарплата", icon: "coins" },
  { kind: "income", name: "Бизнес", icon: "chart" },
  { kind: "income", name: "Подработка", icon: "tools" },
  { kind: "income", name: "Самозанятость", icon: "receipt" },
  { kind: "income", name: "Инвестиции", icon: "chart" },
  { kind: "income", name: "Подарки", icon: "gift" },
  { kind: "income", name: "Возвраты", icon: "transfer" },
  { kind: "income", name: "Продажа имущества", icon: "tag" },
  { kind: "income", name: "Другое", icon: "other" },
] as const;
