export const ICON_LIBRARY = [
  { id: "basket", label: "Продукты" },
  { id: "utensils", label: "Кафе и рестораны" },
  { id: "home", label: "Дом" },
  { id: "receipt", label: "Платежи и налоги" },
  { id: "bus", label: "Транспорт" },
  { id: "car", label: "Автомобиль и такси" },
  { id: "health", label: "Здоровье" },
  { id: "beauty", label: "Красота" },
  { id: "clothes", label: "Одежда" },
  { id: "film", label: "Развлечения" },
  { id: "repeat", label: "Подписки" },
  { id: "book", label: "Книги" },
  { id: "plane", label: "Путешествия" },
  { id: "baby", label: "Дети" },
  { id: "gift", label: "Подарки" },
  { id: "bank", label: "Банк и кредиты" },
  { id: "phone", label: "Связь" },
  { id: "business", label: "Работа и бизнес" },
  { id: "coins", label: "Зарплата" },
  { id: "chart", label: "Инвестиции" },
  { id: "transfer", label: "Возвраты и переводы" },
  { id: "tag", label: "Продажи" },
  { id: "target", label: "Цели" },
  { id: "palm", label: "Отпуск" },
  { id: "laptop", label: "Техника" },
  { id: "education", label: "Образование" },
  { id: "wallet", label: "Кошелёк" },
  { id: "coffee", label: "Кофе" },
  { id: "pet", label: "Питомцы" },
  { id: "sport", label: "Спорт" },
  { id: "tools", label: "Подработка и ремонт" },
  { id: "other", label: "Другое" },
] as const;
export type IconId = (typeof ICON_LIBRARY)[number]["id"];
const legacy: Record<string, IconId> = {
  "🛒": "basket",
  "🍽️": "utensils",
  "🏠": "home",
  "🧾": "receipt",
  "🚌": "bus",
  "🚗": "car",
  "🩺": "health",
  "✨": "beauty",
  "👕": "clothes",
  "🎬": "film",
  "🔁": "repeat",
  "📚": "book",
  "✈️": "plane",
  "🧸": "baby",
  "🎁": "gift",
  "🏦": "bank",
  "📱": "phone",
  "💼": "business",
  "💰": "coins",
  "📈": "chart",
  "↩️": "transfer",
  "🏷️": "tag",
  "🎯": "target",
  "🌴": "palm",
  "💻": "laptop",
  "🎓": "education",
  "🏡": "home",
  "🚕": "car",
  "📑": "receipt",
  "📊": "chart",
  "🛠️": "tools",
  "•••": "other",
};
/** Accept old backups without changing category identity or transaction links. */
export function normalizeIconId(value: string): IconId {
  return (
    ICON_LIBRARY.find((icon) => icon.id === value)?.id ??
    legacy[value] ??
    "other"
  );
}
